# Fix for "Using kotlin.sourceSets DSL to add Kotlin sources is not allowed with built-in Kotlin"
android.disallowKotlinSourceSets=false

# Typical Android Studio default properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
